### ISSUE TITLE
How to save ResultRange?

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#103]
I have got follow code:

ResultRange MySQLTablesRange = mysqlconnection.query(`SELECT * FROM TABLENAME`);
auto historysensor = MySQLTablesRange.array.map!(a => a[0].coerce!string).filter!(a=>a.canFind("historysensor"));
auto historygps = MySQLTablesRange.array.map!(a => a[0].coerce!string).filter!(a=>a.canFind("historygps"));

The problem is that first call:
`auto historysensor = MySQLTablesRange.array`
make result `MySQLTablesRange` empty, so in second I can't get any data from it. It seems that there is should be methods like `save`

**Comment by Abscissa** [comment]
`query` returns an input range. Input ranges, by definition, don't support .save or otherwise iterating more than once. Please see [D's newsgroup forums](https://forum.dlang.org/group/learn) for help understanding D's ranges and how to use and convert them.

In most cases, iterating an SQL result set more than once isn't usually necessary (and wastes memory). But if you do need to, note that mysql-native has a convenience function, [querySet](http://semitwist.com/mysql-native/mysql/commands/querySet.html) to download the entire result set at once and return the entire set of rows as a random-access range instead.
