### ISSUE TITLE
Invalid value for decimal column type when using prepared statement

### ISSUE THREAD

**Issue by jcrapuchettes** [mysql-d/mysql-native#111]
I have a table with a `decimal(11,4)` column. If I query that table with a prepared statement, I get a value of 2.40588e-57. If I query the table with a regular query, I get the actual value.

Attached is a [diff](https://github.com/mysql-d/mysql-native/files/1052981/integration.d.diff.txt) for the integration.d module that will add tests for this specific situation. Of the 4 sets of tests, the third will fail. That test can be made to work by moving the `case SQLType.NEWDECIMAL:` ([packet_helpers.d:681](https://github.com/mysql-d/mysql-native/blob/master/source/mysql/protocol/packet_helpers.d#L681)) down to the string section, but doing the move will cause the other tests to fail.

**Comment by Abscissa** [comment]
Looks like the fix for #39 was incorrect after all. Finally found some documentation on NEWDECIMAL, courtesy of MariaDB:

https://mariadb.com/kb/en/mariadb/resultset-row/#decimal-binary-encoding

Apperently, MySQL/MariaDB treats NEWDECIMAL as a string. Since converting floatings from text representation to native binary decimal/double/real/etc is inherently lossy, I'm thinking the best thing to do is simply expose NEWDECIMAL as a string as well, and let the client code handle the conversion however it code sees fit.

I still need to look closer into out the the unittest cases you priovided...fingers crossed that hopefully won't reveal any unpleasant surprises...
