### ISSUE TITLE
lastInsertId not easily obtained from a prepared structure

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#115]
Assume I have an autoincrement table, when I execute a prepared "INSERT" statement, I would like to be able to get the auto-generated id. This is only accessible from the `Connection` object, and `PreparedImpl` does not expose its connection. Previously, it was in `Command`, but that is now deprecated. It's fairly easy to add, I think this would do it:

```D
struct PreparedImpl {
...
@property lastInsertID() { return _conn.lastInsertID(); }
}
```

**Comment by Abscissa** [comment]
The problem with that (and this is the same reason lastInsertID was changed to *only* be accessible from Conenction) is because asking the server for the last insert ID, always retreives the last insert ID *of the current conenction*, not of any particular statement.

If a lastInsertID accessor it was added to Prepared, that would lead to same misleading bug-prone behavior that exited in the old Command struct:

1. Insert a row to one table using myPreparedStatementA
2. Insert a row to *any* table using *any* other statement, prepared or otherwise.
3. Call `myPreparedStatementA.lastStatementID`.

The result will NOT be the ID from step 1 (as suggested by the syntax `myPreparedStatementA.lastStatementID`). Instead, it will be the ID from step 2. This would be counter-intuitive and error-prone.

AFAIK, there's no way around this other than to automagically ask the server for last ID immediately after all `exec*()` calls. But I don't beleive that sort of additional behind-the-scenes overhead would be appropriate for a low-level driver like this.

**Comment by schveiguy** [comment]
This doesn't make sense, `Connection._insertID` is a field, not a function. You don't "ask" the server for the id, it has already told you. So the "overhead" is already happening.

I'll be straight with you, 99.999% of the time, when you want the last insert id, you get it *immediately* after inserting a row. The idea that you do some other things is pretty far fetched. At this point, mysql-native doesn't provide me a nice one-liner to execute queries with parameters, so I still have my wrapper type. This guy needs to get the last insert id for future reference (I don't mind the overhead). Unfortunately this means I need to store the `Prepared` instance (for re-calling if needed), *and* the Connection (for getting the last insert ID).

The *correct* way to do this is to let the user decide where to put the insert id. IMO, `Connection` shouldn't even store it! Especially since it can change between calls. This smells of errno vintage...

Two options I can see as a compromise:
1. provide an accessor to the connection object. I'm perfectly fine calling `stmt.conn.lastInsertID`
2. provide a ref parameter to `PreparedImpl.exec` that allows you to capture the insert id.

A slightly related issue: If I was going to insert multiple rows into the DB with the same prepared statment, before each call I would do `cmd.purgeResult`. This is also unavailable from the `Prepared` struct, so even with this fix I still need a `Connection` reference. Or do I? I'm not 100% sure, because I don't remember why I put that call in there (it may have been a defensive call). Do you have any comment on that? Is it safe to assume the `Prepared` can call `exec` again without having to purge the result?

**Comment by Abscissa** [comment]
> This doesn't make sense, `Connection._insertID` is a field, not a function. You don't "ask" the server for the id, it has already told you. So the "overhead" is already happening.

Oops, you're right. I was trying to speak from memory and got mixed up (there are other SQL libs I've used in the past where I'd have to issue an SQL command to get the last insert ID - guess that left a big residual impression!). In this case it isn't even an overhead - the server returns the ID as part of it's "OK" packet.

> I'll be straight with you, 99.999% of the time, when you want the last insert id, you get it *immediately* after inserting a row. The idea that you do some other things is pretty far fetched.

Yes, but in general, if an object still exists, then accessing its members should either return the correct result *for the given object* or otherwise bail (ex: throw, etc). What it should never do is return the wrong value.

Luckily, I was wrong about the internals of lastInsertID, so giving Prepared a lastInsertID field that always behaves correctly (with no overhead for cases when the ID isn't needed) should be trivial. I'll do that.

Note that (ugh, assuming I'm actually remembering correctly this time) the old Command struct's  lastInsertID just simply forwarded the value from Connection.lastInsertID, which could then become out-of-date as I described. Due to some weridness with the code's overall articecture back then (Command was multi-purpose to a fault), I don't think that would've been so easy to fix as it will be now.

> At this point, mysql-native doesn't provide me a nice one-liner to execute queries with parameters,

Oh, that's a good idea. Ie something that just does the whole prepared-statement thing behind-the-scenes so you can just do a one-off SQL command with parametarized values in just once function call.

Filed so I don't forget: #118

> The *correct* way to do this is to let the user decide where to put the insert id. IMO, `Connection` shouldn't even store it! Especially since it can change between calls. This smells of errno vintage...

Yea, there's a lot about mysqln that's reminded me of errno-era programming. Such as nearly everything about the old Command struct (a big part of why I was glad to refactor that struct into oblivion). Clearly though, there's still some more to do on that front.

> A slightly related issue: If I was going to insert multiple rows into the DB with the same prepared statment, before each call I would do `cmd.purgeResult`. This is also unavailable from the `Prepared` struct, so even with this fix I still need a `Connection` reference. Or do I? I'm not 100% sure, because I don't remember why I put that call in there (it may have been a defensive call). Do you have any comment on that? Is it safe to assume the `Prepared` can call `exec` again without having to purge the result?

Hmm, good question. If I'd been asked that some months ago when the big API refresh was still fresh in my mind I'd probably have been able to answer straight-away...I know I did a lot of work eliminating some dangerous corner-cases relating to purging and not-perging results...but I don't rember offhand whether results purging is done automatically when needed, or if it throws a "Hey, there's still results pending, ya gotta either read them or purge them" exception.

Would you mind copy-paste re-posting that question as a new issue so I'll rememeber to get back to you on that?

**Comment by Abscissa** [comment]
To summarize (largely for my own future reference):

When a prepared statement is executed, the lib should automatically copy `Connection.lastInsertID` into a `PreparedImpl.lastInsertID`.

Consider ditching `Connection.lastInsertID` entirely...although there would still need to be a way to get that value when using non-prepared statements.
