### ISSUE TITLE
Store buffers in connection object?

### ISSUE THREAD

**Issue by Marenz** [mysql-d/mysql-native#122]
How open are you to the idea to store either a buffer or arbitrary user-data in the `Connection` object?

The motivation is that I could store my format buffer for SQL strings inside the connection object and reuse that buffer for every new query (I would set it to `assumeSafeAppend()` so that it would reuse the memory).

If you like the idea this could even be expanded so that you could directly write

`conn.query("SELECT a, b ,c FROM example WHERE d = %s", my_d_variable)` and it would use the internal buffer to format that string.

**Comment by Abscissa** [comment]
As far as adding decidated fields to types for "user can store their own misc data here", I'm not a fan of that. It breaks encapsulation in particularly messy and dangerous ways. Plus, it doesn't enable anything that can't be accomplished much more cleanly/safely via composition (and D features like templates and alias this help make the composition approach particularly easy and painless).

But I am open to specific proprosals for decreasing the lib's reliance on GC, or otherwise improving the lib's memory usage.

However, if you're using format strings to generate SQL, then I strongly recommend using prepared statements instead: They don't require a new string to be generated/allocated (since they're handled purely on the server-side), and far more importantly, they provide far better safety guarantees (ie, virtually eliminates SQL injection attacks without ever needing to remember to do "proper" escaping).

**Comment by Marenz** [comment]
I plan to use prepared statements where I can, but some of my queries use `IN` or do an `INSERT .. ON DUPLICATE UPDATE ...` with a long list of rows to update/insert and those won't work with prepared statements.

**Comment by Marenz** [comment]
Also, there is still the issue of having to manage the prepared statements per connection ;)-

**Comment by Abscissa** [comment]
Managing prepared statements per connection is #95.

Closing because the main question's been answered.
