### ISSUE TITLE
Allow charset to be defined in connect string / c'tor

### ISSUE THREAD

**Issue by Marenz** [mysql-d/mysql-native#129]
I can't define an initial charset for my connection, instead I need to do for example `SET CHARACTER SET 'utf8mb4'` as the very first sql instructions. When this is used in combination with mysql pools, it becomes non-trivial as I can't easily hook into when a new connection is created

**Comment by Abscissa** [comment]
Good catch. It would be nice for the connection string to support this.

However, it does make me think though, between this and prepared statments (and god knows what else) it would seem that any connection pool, in general (whether mysqln or otherwise), should ideally offer a generic ability to hook into any "connection created/ended" event.

Ultimately, mysqln's connection pools are provided by vibe.d, so I'll check into what vibe.d may (or may conceivably) offer and go from there.  At the very least, mysqln could offer it as an enhancement.

**Comment by Abscissa** [comment]
> On latest master, the connection pool now supports custom "onNewConnection" callback. So once that's released, this issue (and any similar needs) can at least be worked around easily enough.

Now available in v2.0.0

**Comment by schveiguy** [comment]
Seems like this is resolved.
