### ISSUE TITLE
No support for type modifiers in prepared statement parameters.

### ISSUE THREAD

**Issue by nomad-software** [mysql-d/mysql-native#13]
Currently there is no support for const types for prepared statement parameters. e.g.:

...
const(int) id = 111;
command.bindParameter(id, 0);
...

Exception:

Unsupported parameter type const(int)

**Comment by Abscissa** [comment]
Progress so far:

It seems the main problem here is the internal function `analyseParams`. When the parameters are set, they are stored in an array of Variant. Converting these to actual packet data is handled by the `analyseParams` function (currently inside `mysql.connection.ProtocolPrepared`, but since it deals with the low-level socket communications it's going to get moved to somewhere inside `mysql.protocol`).

The `analyseParams` function determines a value's type by `switch`-ing on `Variant.type.toString`. The reason type modifiers are not currently permitted is because this changes the string name of the type (ex:`"const(int)"` instead of `"int"`).

So to fix this, that needs to be dealt with. I'd rather avoid a string-processing solution, if possible (that seems like diving down a rabbit hole best avoided if we can). Adding "case" entries for every `"const(xxx)"`/`"immutable(xxx)"`/etc possibility might be feasible (albiet tedious) if common implementation details for similar types are abstracted out. Though I don't know how much trouble that may pose if `shared` enters the mix, or what other attributes may need to be dealt with.

Ideally, I'd like a solution based around Unqual (or something to a similar effect), but regardless, this issue is long past due. It needs to finally get resolved, one way or another.
