### ISSUE TITLE
SQL types to D types documentation

### ISSUE THREAD

**Issue by Marenz** [mysql-d/mysql-native#136]
Whenever I write an SQL query, I kind of have to guess what types my variables storing the result should have (or what I'll use as the `.get` argument.

Looking through the code, I extracted this mapping info:

```
TINYINT -> (u)byte
SMALLINT -> (u)short
MEDIUMINT -> (u)int
INT -> (u)int
BIGINT -> (u)long
FLOAT -> float
DOUBLE -> double
TIMESTAMP -> DateTime
TIME -> TimeOfDay
YEAR -> ushort
DATE -> Date
DATETIME -> DateTime
VARCHAR, ENUM, SET, VARSTRING, STRING, DECIMAL, NUMERIC -> string
BIT -> bool
TINYBLOB, MEDIUMBLOB, BLOB, LONGBLOB -> string / ubyte[] (?)
```

But I don't know a good place to put it. The readme? Somewhere in the docs?

**Comment by Abscissa** [comment]
On October 6, 2017 3:20:17 PM EDT, "Mathias L. Baumann" <notifications@github.com> wrote:
>Whenever I write an SQL query, I kind of have to guess what types my
>variables storing the result should have (or what I'll use as the
>`.get` argument.
>
>Looking through the code, I extracted this mapping info:
>
>```
>TINYINT -> (u)byte
>SMALLINT -> (u)short
>MEDIUMINT -> (u)int
>INT -> (u)int
>BIGINT -> (u)long
>FLOAT -> float
>DOUBLE -> double
>TIMESTAMP -> DateTime
>TIME -> TimeOfDay
>YEAR -> ushort
>DATE -> Date
>DATETIME -> DateTime
>VARCHAR, ENUM, SET, VARSTRING, STRING, DECIMAL, NUMERIC -> string
>BIT -> bool
>TINYBLOB, MEDIUMBLOB, BLOB, LONGBLOB -> string / ubyte[] (?)
>```
>
>But I don't know a good place to put it. The readme? Somewhere in the
>docs?

Good point. That info should probably be predominant enough to trip over so no one has to go looking for it.

I'm thinking maybe:

1. In the readme right between the "primary interfaces" and "basic example" section.

and also in:

2. a ddoc macro defined somewhere common and instantiated in all relevant parts of the docs, like here:

http://semitwist.com/mysql-native-docs/v1.0.0/mysql/commands.html

and

http://semitwist.com/mysql-native-docs/v1.0.0/mysql/prepared.html

and the docs for all the various query/exec functions (and anything else relevant)

Alternatively, instead of #2 a special page could be added to the docs for this chart, and all those doc pages could link to it. It should probably still go in the readme too.
