### ISSUE TITLE
please remove dub.selections.json from source control and gitignore it

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#140]
I've always argued that _dub.selections.json_ should be excluded from source control, now Sönke himself is recommending it shouldn't be used for libraries:
https://github.com/dlang/dub/issues/1245

please remove from the repo.

**Comment by Abscissa** [comment]
It's in there for the test builds so that those are predictably reproducable.

Reading that issue and the linked previous discussion, it sounds to me that he's only saying those files are not *necessary* in libs and that *dub itself* shouldn't default to generating them. I don't see an argument that libraries in general *should* exclude them.

And, AIUI, I don't think dub actually uses a library's `dub.selections.json` when the library is being used as a library dependncy of another project, so I doubt the file's existence in the repo could cause any problems.

@s-ludwig: Am I off-base here, or is that about it? Any input?

**Comment by s-ludwig** [comment]
Fully agree. Usually it will be less prolematic to exclude the selections for libraries, but nothing speaks against including them if they are used to implement a partiular testing process (ideally there should be a `dub upgrade` step though, so that the compatibility with the latest matching dependency versions is also verified). It's also true that the selections get ignored for dependencies.

**Comment by SingingBush** [comment]
the problem is just that when building/running tests you may not detect problems that your users experience due to different dependency versions. changin the travis build to run tests after a `dub upgrade` would be a great help.

**Comment by Abscissa** [comment]
> the problem is just that when building/running tests you may not detect problems that your users experience due to different dependency versions.

Unfortunately, that's a potential problem regardless of dub.selections.json. It's one I have to admit I've mostly been pushing out of my mind just to maintain my own sanity, because really, the only way around it is to test on all the various combinations of all the various versions of the direct and indirect dependencies - and that has all kinds of difficulties.

> changin the travis build to run tests after a dub upgrade would be a great help.

Maybe a middle ground would be ideal: Keep dub.selections.json at the minimum supported versions of all deps (potentially a pain to figure out though, unless dub offers some easy way to obtain this list). Then, run the tests both before *and* after a dub upgrade.

Sonke: Dub upgrade does its best to select the latest possible versions of everything, right? Also, what is dub's default behavior when there is no dub.selections.json? Does it also try for the latest everything, same as "dub upgrade"? Is there a simple way to request dub do the opposite, and try for the earliest version of everything that still satisfies all dub.sdl constraints?

**Comment by Abscissa** [comment]
Here's what we *really* need, and to be honest, I think this is extremely important for the D ecosystem: 

DUB needs to know what compiler versions each version of each package will work with, and what DMDFE version is currently being used. Period. And it needs to take this into account during dependency resolution.

A D package manager that doesn't do this will *never* be able to avoid compatibility issues reliably. Period. A D package manager that *does*...*can* be made to avoid  compatibility issues reliably.

Honestly, anything mysql-native (or any other library) does to try to deal with dub.selections.json and compatability across versions of dependencies is *guaranteed* to have holes without DUB treating DMDFE versions like any other project dependency - where version matters.

**Comment by Abscissa** [comment]
Agreed. Adding now.

We should keep in mind though, this still won't guarantee that users won't hit issues from different dependency versions (even if they do a dub upgrade) because dependencies could still have new versions released *after* travis tests mysql-native, and those won't automatically get tested until the next mysql-native commit.

But this should definitely help.
