### ISSUE TITLE
Allow per-connection commands to automatically be executed

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#176]
When using MySQL connection, it may be nice to automatically have it set some options. For example the modes here: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

I wonder if it may be useful to just submit some statements that should be executed every time a connection is re-established (as this is sometimes done transparently in the background).

It also would be good to set these statements in a pool so all connections from that pool do the same thing.

See for example: https://github.com/mysql-d/mysql-native/issues/65#issuecomment-386237514

**Comment by Marenz** [comment]
is `onConnection` not colled for re-establishment?

**Comment by Abscissa** [comment]
> is onConnection not called for re-establishment?

Unfortunately, it currently is not. That was an oversight on my part.

Re-connecting is handled automatically by the Connection class itself, not the pool (although the pool does double-check when it receives a connection and forces an eager reconnect if it's closed). But the onConnection was envisioned and implemented purely as a feature of the pools. So that slipped by me. I'll have to add an on(Re)Connection feature to Connection itself, so then the pool can hook into that to call onConnection upon reconnects.

I'm thinking there are cases the user callbacks may want to know whether it's a new connection or a reconnection, and I'm thinking of making that an (optional, if I can) parameter to the onConnection callback. Only question then is what the default behaviour should be when the user provides a callback that doesn't take the new `bool isReconnection` param. Should it preserve the current behavior (not called on reconnect) to ensure backwards-compatibility, or should it be fixed to trigger upon reconnects? Or should it just be deprecated? I'm thinking preserve current behaviour, but mark it deprecated. Seems to be the best approach.

**Comment by Abscissa** [comment]
I'm going to create a separate ticket for the "no callback called on reconnect" matter, and leave this ticket for "Should some modes be automatically set?" or "Should there be a way to specify commands/modes that's less manual than onConnect?"

**Comment by schveiguy** [comment]
I wasn't aware of the onConnect callback, so yeah, I think It would solve the problem, as long as it's done on reconnects. I'll close this and move discussion to your new issue. I think as long as there is a hook available, it's not necessary to make it more abstract.
