### ISSUE TITLE
It is immposible to use this package anymore without libevent

### ISSUE THREAD

**Issue by Kozzi11** [mysql-d/mysql-native#199]
Because of fixing https://github.com/vibe-d/vibe.d/issues/2155 it is now immposible to use this package anymore without libevent.

I have to manualy edit ```~/.dub/packages/mysql-native-2.3.0/mysql-native/dub.json``` and remove:

```
"subConfigurations": {
		"vibe-d:core": "libevent"
	},
```

to make it works again

**Comment by Kozzi11** [comment]
If you look at:
https://dub.pm/package-format-sdl.html#build-settings
to a ```subConfiguration``` part desvription it says:

> Locks a dependency (first argument) to a specific configuration (second argument); see also the configurations section - this setting **does not support the platform attribute**

**Comment by Kozzi11** [comment]
https://github.com/mysql-d/mysql-native/commit/ec851956e579bab8d00b1ae89a5344a2babce2e3

**Comment by itkfm** [comment]
Seems like this issue is getting more and more presence:
- #201 
- https://forum.dlang.org/post/ziryinicbqcgjvqlytwu@forum.dlang.org

**Comment by itkfm** [comment]
Maybe this could be fixed in DUB. Is there a reason why `subConfigurations` does _not_ support platform attributes?

**Comment by Abscissa** [comment]
On October 10, 2019 6:37:12 AM EDT, itkfm <notifications@github.com> wrote:
>Maybe this could be fixed in DUB. Is there a reason why
>`subConfigurations` does _not_ support platform attributes?

That workaround doesn't appear to be needed anymore anyway. I'm removing the offending line.

**Comment by Abscissa** [comment]
Correction: The workaround *does* appear to still be needed on OSX after all (even with the latest vide-core), but it clearly causes too much trouble on other platforms so I'm still removing it anyway.

I think what I'm going to do is declare official OSX support to be phobos-sockets-only, not vibe, until vibe-core gets its out-of-the-box OSX support sorted out and working (Turns out, even vibe-core itself isn't even officially/successfully tested on OSX yet: https://github.com/vibe-d/vibe-core/pull/183 ).

**Comment by Abscissa** [comment]
Now fixed. The munged osx "fix" has been removed in master.
