### ISSUE TITLE
bindParameters example wrong?

### ISSUE THREAD

**Issue by bhechinger** [mysql-d/mysql-native#50]
So taking from the comments in protocol/commands.d I tried this code:

``` D
command.sql = "SELECT * FROM myTable WHERE myColumn IN (?, ?)";
command.prepare;
Variant[] va;
va.length = 2;
command.bindParameters(va);
va[0] = "foo";
va[1] = "bar";
results = command.execPreparedResult();
```

This failed with:

```Unbound parameter 0```

I changed the code to:

``` D
command.sql = "SELECT * FROM myTable WHERE myColumn IN (?, ?)";
command.prepare;
Variant[] va;
va.length = 2;
va[0] = "foo";
va[1] = "bar";
command.bindParameters(va);
results = command.execPreparedResult();
```

And it worked. Is the example wrong?

**Comment by Abscissa** [comment]
The bindParameters function explicitly *copies* all the values in the array passed to it, and has done so as far back as the earliest commit in the repository - which *predates* the documented example code (which wouldn't have ever worked correctly).

Because of that, *and* considering it's questionable (and potentially error-prone) in D to *rely on* changing the values after the array's been passed in, I'm going to go ahead as say the example in the doc comments is wrong. I'll fix that.
