### ISSUE TITLE
getNextRow() returns superfluous empty row

### ISSUE THREAD

**Issue by whitebyte** [mysql-d/mysql-native#59]
Consider this small example:

``` D
        // ...
        string query = "SELECT * FROM `documents`";
        auto cmd = new Command(dbconnection, query);
        ulong ra;
        auto result = cmd.execSQL(ra);

        while (cmd.rowsPending) {
            writeln(cmd.getNextRow());
        }
```

Let's say we have a pretty simple SQL table "documents":

``` SQL
+----+--------------+-----------------------------+
| id | title        | content                     |
+----+--------------+-----------------------------+
|  1 | test1        | 1231232312312312            |
|  2 | test2        | 123                         |
|  3 | test3        | 123123123123123             |
+----+--------------+-----------------------------+
```

As we see, there are 3 rows, but this example program writelns 4, not 3, something like this:

```
Row([1, test1 , 1231232312312312 ], [false, false, false])
Row([2, test2, 123], [false, false, false])
Row([3, test3, 123123123123123], [false, false, false])
Row([], [])  <-- ???
```

Is this a bug, or maybe I just missing some point ?

**Comment by Abscissa** [comment]
If you're reading data returned from a query, you should use either ```execSQLResult``` (to grab all results at once and obtain array-like access via ```struct ResultSet```), or ```execSQLSequence``` (to grab the results lazily, row-by-row, via an input range interface ```struct ResultSequence```). The ```execSQL``` function is for queries like INSERT, UPDATE, CREATE, etc that don't return any data other than "rows affected".

ex:

```d
// Eager, random-access, array-like:
auto rows = cmd.execSQLResult();
writeln("Num rows: ", rows.length);

for(row; rows) {
    writeln(row);
}
```

or:
```d
// Lazy, one-row-at-a-time, input range
auto results = cmd.execSQLSequence();

while(!results.empty) {
    writeln(results.front);
    results.popFront();
}
//or:
for(row; results) {
    writeln(row);
}
```

However, I am going to leave this ticket open, because your example code probably *should* either work as expected or trigger an error, it probably shouldn't just give a bad result (Unless that blank row is how mysql indicates there's no more results. I'll have to check into ```Command.rowsPending``` and ```Command.getNextRow```. Maybe those shouldn't even be public, not sure. Needs more digging.)

**Comment by whitebyte** [comment]
Yeah, I know that I should use execSQLResult(), and of course execSQL() returns only bool, but comment block above execSQL() explicitly says that it's possible to get query results with getNextRow(), so I just was making some experiments.

**Comment by whitebyte** [comment]
The problem is in getNextRow() method. It always declares and returns Row, even when EOFPacket reached:

```d
// commands.d
// ...
Row rr;
        packet = _con.getPacket();
        if (packet.isEOFPacket())
        {
            _rowsPending = _pendingBinary = false;
            return rr;
        }
// ...
```

Is this indended behavior?

**Comment by Abscissa** [comment]
Hmm, ok, some notes regarding this:

First of all, there's #96.

But as for the actual issue: It looks like this occurs because it's getNextRow's job in the first place to read the EOF packet and set _rowsPending to false (there's no other way to know the final row has been reached until that happens). But then it needs to return *something*, to fulfill its own function signature, hence the blank row. Only *THEN* is rowsPending finally read as false.

So, *technically* this code from the original post is wrong (ignoring the fact that as of v1.0.0, rowsPending and getNextRow are now part of Connection, not Command):

```d
while(cmd.rowsPending) {
    writeln(cmd.getNextRow());
}
```

It should have been:

```d
while(true) {
    auto row = cmd.getNextRow();
    if(cmd.rowsPending)
        break;

    writeln(row);
}
```

Obviously that's a confusing mess of an API, even for internal functionality, so I think getNextRow should be changed to return a `Nullable!Row` instead of `Row`. (The other option would be to read *ahead* one row on every call, but that means extra storage and the calling code would have to wait for the second row to come across the line before it can receive and process the first row, and the whole loop would have to be primed...It'd work, but I don't really like that approach. So `Nullable!Row` it is.)
