### ISSUE TITLE
Possible bug: Nothing auto-releases statement

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#76]
Command has a function releaseStatement which is supposed to clear the server resource handle for the prepared statement.

There's nothing that automatically does this. Shouldn't the command have a destructor that does this? ResultSequence purges the command, but does not release the statement (and it shouldn't, because you may go and re-execute a new result sequence!). In addition, there's no way to tell if it needs to release a statement (no way to see if it's a prepared statement or not).

I don't know what the protocol specifies. Maybe statements expire after some time and it's not required to clean it up? This is why I say "possible bug".

**Comment by Abscissa** [comment]
The protocol docs don't say much about it, but according to the SQL docs, it does NOT get cleared until the session is terminated (I assume that means connection). On the bright side, prepared statements are specific to a session, and the (adjustable) prepared statement limit is per-session, not per-server. So I don't think it's a big problem since the user *is* still in control of it. But still, sounds like these really should get auto-released when possible.

**Comment by Abscissa** [comment]
This should be fixed in the [new design](http://forum.dlang.org/thread/o6ma0r$20n6$1@digitalmars.com), too. The new interface for prepared statements, Prepared, is reference-counted and releases itself in its dtor.

**Comment by Abscissa** [comment]
Fixed in v1.0.0

**Comment by schveiguy** [comment]
Awesome. Sorry haven't had a chance to look at this, I've had to stick with the old API for now. But I will invest some time soon to try and migrate all my stuff over.
