### ISSUE TITLE
Prepared statement with variables: erroneous parse error

### ISSUE THREAD

**Issue by dhasenan** [mysql-d/mysql-native#84]
Apologies for the length.

In mysql, I can use a prepared statement:

```
mysql> PREPARE stmt1 FROM 'INSERT INTO messages (secure) VALUES (?)';
Query OK, 0 rows affected (0,00 sec)
Statement prepared

mysql> SET @sec = false;
Query OK, 0 rows affected (0,00 sec)

mysql> EXECUTE stmt1 USING @sec;
Query OK, 1 row affected (0,00 sec)
```

In D, the equivalent doesn't work:

```D
bool secure = false;
auto cmd = Command(con);
cmd.sql = `INSERT INTO messages (secure) VALUES (?)`;
cmd.prepare;
cmd.bindParameter(secure, 0);
ulong affected;
cmd.execSQL(affected);
```

The error is:

```
mysql.protocol.packets.MySQLReceivedException@../../.dub/packages/mysql-native-0.1.6/source/mysql/protocol/commands.d(719): MySQL error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1
```

If I substitute the prepared statement's placeholder with a value, I do not get an error and the values are inserted into the table.

Server version: 5.7.15-0ubuntu0.16.04.1 (Ubuntu)

mysql-native version: 0.1.6

**Comment by Abscissa** [comment]
When using prepared statements, you should use `execPrepared` and `execPreparedResult` instead of `execSQL` and `execSQLResult`.

However, mysql-native should clearly, at the very least, catch this and provide a more meaningful exception message. Ideally, the API should be adjusted so you don't even need to make a choice.

I'm closing this as invalid, but I'll create a new issue to fix the confusion mysql-native causes in this situation. If you still get the same error even when using `execPrepared`, then please re-open this issue.
