### ISSUE TITLE
The vibed app do not works if db credentials do now have select permissions 

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#98]
I found very strange bug. My vibed apps stops work after changing config.ini file.

I changed user name, but did not give him any permissions. In result vibed app was not able even to listen any inbound connections.

And the problem was in driver. I think users should be informed that current user can't work with DB (exception or so). And it's very strange that vibed stop listening connections.

**Comment by Abscissa** [comment]
It does appear that mysql servers (or at least the mariadb server I tried) reject login attempts for users that don't have any permissions with `Authentication failure: Access denied for user [user name] to database [schema name]" (kinda makes sense, since such a user wouldn't be able to do anything while logged in anyway).

But, that's has nothing to do with the mysql-native client driver. And, most likely by design, there is no way for the client (ie, mysql-native) to know why the server rejected a login. So there's really nothing for mysql-native to do here.

As for a rejected login preventing a vibe application from listening for connections, I'm unable to reproduce such a problem. Sounds like a problem in the application code. If there really is such an issue being caused by mysql-native, I'd need a reproducible, minimized test case to work with.
